TasteIt/Web/TasteIt.Web/Models/Recipe/CommentViewModel.cs
namespace TasteIt.Web.Models.Recipe
{
    using System.ComponentModel.DataAnnotations;
    using AutoMapper;
    using Infrastructure.Mapping;
    using TasteIt.Data.Models;

    public class CommentViewModel : IMapFrom<Comment>, IHaveCustomMappings
    {
        public int Id { get; set; }
        
        [Required]
        [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 3)]
        public string Content { get; set; }
        
        public string PostedById { get; set; }

        public string PostedBy { get; set; }

        public string PostedByImage { get; set; }

        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<Comment, CommentViewModel>()
                   .ForMember(x => x.PostedBy, opt => opt.MapFrom(x => (x.PostedBy.FirstName + " " + x.PostedBy.LastName)));

            configuration.CreateMap<Comment, CommentViewModel>()
                   .ForMember(x => x.PostedByImage, opt => opt.MapFrom(x => x.PostedBy.ImageURL));
        }
    }
}

TasteIt/Web/TasteIt.Web/Models/Recipe/OccasionViewModel.cs
namespace TasteIt.Web.Models.Recipe
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Infrastructure.Mapping;
    using TasteIt.Data.Models;

    public class OccasionViewModel : IMapFrom<Occasion>
    {
        public int Id { get; set; }
        
        [Required]
        [Index(IsUnique = true)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 5)]
        public string Name { get; set; }

        public string OccasionImage { get; set; }

        public IEnumerable<RecipeViewModel> Recipies { get; set; }
    }
}

TasteIt/Web/TasteIt.Web/Models/Recipe/RecipeInputModel.cs
namespace TasteIt.Web.Models.Recipe
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public class RecipeInputModel
    {
        public int Id { get; set; }

        [Required]
        [AllowHtml]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 5)]
        public string Title { get; set; }

        [Required]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public DateTime CreatedOn { get; set; }

        public string CookingTime { get; set; }

        public string RecipeImage { get; set; }

        public string AuthorId { get; set; }

        public string Occasion { get; set; }
    }
}

TasteIt/Web/TasteIt.Web/Models/Recipe/RecipeViewModel.cs
namespace TasteIt.Web.Models.Recipe
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using AutoMapper;
    using Comment;
    using Infrastructure.Mapping;
    using Ingredient;
    using Services.Web;
    using Services.Web.Contracts;
    using TasteIt.Data.Models;

    public class RecipeViewModel : IMapFrom<Recipe>, IHaveCustomMappings
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 5)]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public DateTime CreatedOn { get; set; }

        public string CookingTime { get; set; }

        public Season Season { get; set; }

        public string RecipeImage { get; set; }

        public string AuthorId { get; set; }

        public string Author { get; set; }

        public string Occasion { get; set; }

        public string CountLikes { get; set; }

        public string CountComments { get; set; }

        public IEnumerable<IngredientViewModel> Ingredients { get; set; }

        public IEnumerable<Like> Likes { get; set; }

        public IEnumerable<CommentViewModel> Comments { get; set; }

        public string Url
        {
            get
            {
                IIdentifierProvider identifier = new IdentifierProvider();
                return $"/{identifier.EncodeId(this.Id)}";
            }
        }

        public void CreateMappings(IMapperConfiguration configuration)
        {
            configuration.CreateMap<Recipe, RecipeViewModel>()
                  .ForMember(x => x.AuthorId, opt => opt.MapFrom(x => x.AuthorId));

            configuration.CreateMap<Recipe, RecipeViewModel>()
                   .ForMember(x => x.Author, opt => opt.MapFrom(x => (x.Author.FirstName + " " + x.Author.LastName)));

            configuration.CreateMap<Recipe, RecipeViewModel>()
                   .ForMember(x => x.Occasion, opt => opt.MapFrom(x => x.Occasion.Name));

            configuration.CreateMap<Recipe, RecipeViewModel>()
                  .ForMember(x => x.CountLikes, opt => opt.MapFrom(x => x.Likes.Any() ? x.Likes.Sum(v => (int)v.Value) : 0));

            configuration.CreateMap<Recipe, RecipeViewModel>()
                 .ForMember(x => x.CountComments, opt => opt.MapFrom(x => (x.Comments.Count() - 1)));
        }
    }
}

TasteIt/Web/TasteIt.Web/Models/Recipe/RecipesIndexViewModel.cs
namespace TasteIt.Web.Models.Recipe
{
    using System.Collections.Generic;

    public class RecipesIndexViewModel
    {
        public IEnumerable<OccasionViewModel> Occasions { get; set; }

        public IEnumerable<RecipeViewModel> Recipes { get; set; }
    }
}

TasteIt/Web/TasteIt.Web/Models/Recipe/SeasonViewModel.cs
namespace TasteIt.Web.Models.Recipe
{
    public class SeasonViewModel
    {
        public enum Season
        {
            Spring = 0,
            Summer = 1,
            Autumn = 2,
            Winter = 3
        }
    }
}

TasteIt/Web/TasteIt.Web/Controllers/CommentsController.cs
namespace TasteIt.Web.Controllers
{
    using System;
    using System.Web.Mvc;
    using Infrastructure;
    using Microsoft.AspNet.Identity;
    using Models.Comment;
    using Services.Web.Contracts;
    using TatseIt.Services.Data.Contracts;

    public class CommentsController : BaseController
    {
        private readonly ICommentsService comments;
        private readonly IRecipesService recipes;
        private readonly ISanitizer sanitizer;
        private readonly IIdentifierProvider identifierProvider;

        public CommentsController(ICommentsService comments, IRecipesService recipes, IIdentifierProvider identifierProvider, ISanitizer sanitizer)
        {
            this.comments = comments;
            this.recipes = recipes;
            this.sanitizer = sanitizer;
            this.identifierProvider = identifierProvider;
        }

        public ActionResult Index()
        {
            // var recipe = this.recipes.GetById(id);
            // var recipeComments = this.comments.GetAll()
            //                                   .Where(x => x.RecipeId == recipe.Id)
            //                                   .To<CommentViewModel>()
            //                                   .OrderByDescending(x => x.CreatedOn);
            // 
            // return PartialView(recipeComments);
            return this.View();
        }

        [Authorize]
        public ActionResult Create()
        {
            return this.PartialView();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CommentInputModel comment)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PartialView(comment);
            }

            var newComment = this.comments.Create(this.sanitizer.Sanitize(comment.Content));

            if (this.User.Identity.IsAuthenticated)
            {
                newComment.PostedById = this.User.Identity.GetUserId();
            }

           newComment.CreatedOn = DateTime.UtcNow;

           // string id = this.Url.RequestContext.RouteData.Values["Id"].ToString();
           // var recipe = this.recipes.GetById(id);
           // newComment.RecipeId = recipe.Id;
            this.comments.Add(newComment);

            var resultComment = this.Mapper.Map<CommentInputModel>(newComment);

            return this.PartialView(resultComment);
        }
    }
}

TasteIt/Web/TasteIt.Web/Controllers/IngredientsController.cs
namespace TasteIt.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Infrastructure.Mapping;
    using Models.Ingredient;
    using TatseIt.Services.Data.Contracts;
    using Infrastructure;

    public class IngredientsController : BaseController
    {
        private readonly IIngredientsService ingredients;
        private readonly ISanitizer sanitizer;

        public IngredientsController(IIngredientsService ingredients, ISanitizer sanitizer)
        {
            this.ingredients = ingredients;
            this.sanitizer = sanitizer;
        }

        public ActionResult Index(string selectedLetter)
        {
            var model = new AlphabeticalPagingViewModel { SelectedLetter = selectedLetter };

            model.FirstLetters = this.ingredients.GetFirstLetters();

            if (string.IsNullOrEmpty(selectedLetter) || selectedLetter == "All")
            {
                model.Ingredients = this.ingredients.GetAll()
                                           .OrderBy(p => p.Name)
                                           .To<IngredientViewModel>()
                                           .ToList();

                return this.View(model);
            }
            else
            {
                model.Ingredients = this.ingredients.GetIngredientsWithCommonLetter(selectedLetter.ToLower())
                                         .To<IngredientViewModel>()
                                         .ToList();
            }

            return this.View(model);
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var ingredient = this.ingredients.GetById(id);
            var viewModel = this.Mapper.Map<IngredientViewModel>(ingredient);

            return this.View("Details", viewModel);
        }

        [HttpGet]
        public ActionResult ShowList(string firstLetter)
        {
            var ingredients = this.ingredients.GetIngredientsWithCommonLetter(firstLetter.ToLower())
                                             .To<IngredientViewModel>()
                                             .ToList();

            return this.View("ShowList", ingredients);
        }

        [Authorize]
        public ActionResult Create()
        {
            return this.PartialView();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IngredientViewModel ingredient)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PartialView(ingredient);
            }

            var newIngredient = this.ingredients.Create(
                this.sanitizer.Sanitize(ingredient.Name), 
                this.sanitizer.Sanitize(ingredient.IngredientDetails), 
                this.sanitizer.Sanitize(ingredient.IngredientImage));

            var resultIngredient = this.Mapper.Map<IngredientViewModel>(newIngredient);

            this.TempData["Notification"] = "Ingredient was successfully created!";

            return this.PartialView(resultIngredient);
        }
    }
}

TasteIt/Web/TasteIt.Web/Controllers/RecipeController.cs
namespace TasteIt.Web.Controllers
{
    using Infrastructure.Mapping;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using TasteIt.Web.Models.Recipe;
    using TatseIt.Services.Data.Contracts;

    public class RecipeController : Controller
    {
        private readonly IRecipesService recipes;

        public RecipeController(IRecipesService recipes)
        {
            this.recipes = recipes;
        }

        // GET: Recipe
        public ActionResult Index()
        {
            var allRecipes = this.recipes
                                  .GetAll()
                                  .To<RecipeViewModel>()
                                  .ToList();

            return this.View(allRecipes);
        }
    }
}

TasteIt/Web/TasteIt.Web/Controllers/RecipesController.cs
namespace TasteIt.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Infrastructure;
    using Infrastructure.Mapping;
    using Microsoft.AspNet.Identity;
    using TasteIt.Web.Models.Recipe;
    using TatseIt.Services.Data.Contracts;

    public class RecipesController : BaseController
    {
        private readonly IRecipesService recipes;
        private readonly IOccasionsService occasions;
        private readonly ISanitizer sanitizer;

        public RecipesController(IRecipesService recipes, IOccasionsService occasions, ISanitizer sanitizer)
        {
            this.recipes = recipes;
            this.occasions = occasions;
            this.sanitizer = sanitizer;
        }

        // GET: Recipe
        public ActionResult Index()
        {
            var occasions = this.occasions.GetAll()
                                        .To<OccasionViewModel>()
                                        .ToList();
            
            var recipes = this.recipes.GetAll()
                                  .To<RecipeViewModel>()
                                  .ToList();
            
            var viewModel = new RecipesIndexViewModel
            {
                Occasions = occasions,
                Recipes = recipes
            };

            if (viewModel == null)
            {
                return this.Redirect("/");
            }

            return this.View(viewModel);
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            var recipe = this.recipes.GetById(id);
            var viewModel = this.Mapper.Map<RecipeViewModel>(recipe);

            return this.View("Details", viewModel);
        }

        [HttpGet]
        public ActionResult GetBySeason(string season)
        {
            var recipes = this.recipes.GetBySeason(season)
                                      .To<RecipeViewModel>()
                                      .ToList();

            var viewModel = new RecipesIndexViewModel
            {
                Recipes = recipes
            };

            if (viewModel == null)
            {
                return this.Redirect("/");
            }

            return this.View(viewModel);
        }

        [HttpGet]
        public ActionResult GetByOccasion(string occasion)
        {
            var recipes = this.recipes.GetByOccasion(occasion)
                                      .Where(x => x != null)
                                      .To<RecipeViewModel>()
                                      .ToList();

            var viewModel = new RecipesIndexViewModel
            {
                Recipes = recipes
            };

            if (viewModel == null)
            {
                return this.Redirect("/");
            }

            return this.View(viewModel);
        }

        [Authorize]
        public ActionResult Create()
        {
            return this.PartialView();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RecipeInputModel recipe)
        {
            if (!this.ModelState.IsValid)
            {
                return this.PartialView(recipe);
            }

            var newRecipe = this.recipes.Create(
                this.sanitizer.Sanitize(recipe.Title),
                this.sanitizer.Sanitize(recipe.Description),
                this.sanitizer.Sanitize(recipe.CookingTime),
                this.sanitizer.Sanitize(recipe.RecipeImage));

            if (this.User.Identity.IsAuthenticated)
            {
                newRecipe.AuthorId = this.User.Identity.GetUserId();
            }
            
            newRecipe.CreatedOn = DateTime.UtcNow;

            this.recipes.Add(newRecipe);

            var resultRecipe = this.Mapper.Map<RecipeInputModel>(newRecipe);

            this.TempData["Notification"] = "Recipe was successfully added!";

            return this.PartialView(resultRecipe);
        }
    }
}

TasteIt/Web/TasteIt.Web/Views/Recipes/Create.cshtml
@model TasteIt.Web.Models.Recipe.RecipeInputModel

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Recipe</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CookingTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CookingTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CookingTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecipeImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecipeImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecipeImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Occasion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Occasion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occasion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div id="add-ingredient">
</div>
<p>
    @Ajax.ActionLink("Add Ingredient", "Create", "Ingredients", new AjaxOptions()
       {
           HttpMethod = "GET",
           InsertionMode = InsertionMode.Replace,
           UpdateTargetId = "add-ingredient"
       })
</p>



<div>
    @Html.ActionLink("Back to Recipes", "Index", null, new { @class = "btn btn-primary"})
</div>

TasteIt/Web/TasteIt.Web/Views/Recipes/Details.cshtml
@model TasteIt.Web.Models.Recipe.RecipeViewModel
@{
    ViewBag.Title = "Details";
}

<div>
    <h2 class="detail-title">@Html.DisplayFor(@model => model.Title)</h2>
    <p><i>Recipe autor: @Html.DisplayFor(@model => model.Author)</i></p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-1">
            <div class="well text-center">
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="row" data-id="@Model.Id" data-action="up"><span class="glyphicon glyphicon glyphicon-thumbs-up"></span></div>
                }
                <div class="row" data-id="@Model.Id" data-action="recipesCount">@Model.CountLikes</div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="row" data-id="@Model.Id" data-action="down"><span class="glyphicon glyphicon-thumbs-down"></span></div>
                }
            </div>
        </div>

        <div class="recipe-details col-md-6 detail-text">
            <div>
                <p><strong>Preparation time: </strong></p>
                <p>@Html.DisplayFor(@model => model.CookingTime)</p>
            </div>

            <p><strong>Ingredients:</strong></p>
            @if (@Model.Ingredients == null)
            {
                return;
            }
            else
            {
                foreach (var item in @Model.Ingredients)
                {
                    <div>
                        @item.Quantity
                        @Html.ActionLink(item.Name, "/Details" + item.Url, "Ingredients")
                    </div>
                }
            }
        </div>

        <div class="col-md-4">
            <img class="recipe-image" src="@Html.DisplayFor(@model =>model.RecipeImage)" />
        </div>

    </div>
    <br />

    <div class="detail-text">
        <div>
            <p><strong>Preparation:</strong></p>
            @Html.DisplayFor(@model => model.Description)
        </div>
    </div>
</div>
<br />

@*<div class="row">
        @Html.Action("Create", "Comments", new { id = Model.Id })
   </div>
*@


@if (this.User.Identity.IsAuthenticated)
{
    <p>
        @Ajax.ActionLink("Add Comment", "Create", "Comments", new AjaxOptions()
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "create-comment"
        })
    </p>

    <div id="create-comment"></div>
}


<h3><strong>Comments:</strong></h3>
<div>
    <div class="container">
        @if (@Model.Comments == null)
            {
                return;
            }
            else
            {
                foreach (var comment in @Model.Comments)
                {
                <div class="row">
                    <div class="col-md-2">
                        @if (comment.PostedByImage == null)
                        {
                            <img class="comment-image" src="http://www.adsitsolutions.com/images/icons/grey/home-user-icon.png" />
                        }
                        else
                        {
                            <img class="comment-image" src="@comment.PostedByImage" />
                        }
                    </div>
                    <div class="col-md-12">
                        <h4 class="logo">@comment.PostedBy</h4>
                        <div class="comment-content">@comment.Content</div>
                    </div>
                </div>
            }
        }
    </div>
</div>
<br />

<div>
    @Html.ActionLink("More recipes", "" , "Recipes", null, new {@class="btn btn-primary" })

</div>



@section scripts{
    <script>
        $("div[data-action='up'").click(function () {
            var id = $(this).attr("data-id");
            likeClick(id, 1);
        });
        $("div[data-action='down'").click(function () {
            var id = $(this).attr("data-id");
            likeClick(id, -1);
        });

        function likeClick(id, likeType) {
            $.post("/Likes/Like", { recipeId: id, likeType: likeType },
                function (data) {
                    var newLikesCount = data.Count;
                    $("div[data-action='recipesCount'][data-id='" + id + "']").html(newLikesCount)
                });
        }
    </script>
}

TasteIt/Web/TasteIt.Web/Views/Recipes/GetByOccasion.cshtml
@model TasteIt.Web.Models.Recipe.RecipesIndexViewModel
@{
    ViewBag.Title = "GetByOccasion";
}

<h2>Recipes By Occasion</h2>


@if (Model == null)
{
    <div>No recipes in this occasion!</div>
}

@Html.Partial("_RecipePartial")

@Html.ActionLink("Back to recipes", "", "Recipes", null, new { @class = "btn btn-primary" })

TasteIt/Web/TasteIt.Web/Views/Recipes/GetBySeason.cshtml
@model TasteIt.Web.Models.Recipe.RecipesIndexViewModel
@{
    ViewBag.Title = "GetBySeason";
}

<h2>Recipes By Season</h2>

@if (Model == null)
{
    <div>No recipes in this season!</div>
}

@Html.Partial("_RecipePartial")

@Html.ActionLink("Back to recipes", "", "Recipes", null, new { @class = "btn btn-primary" })

TasteIt/Web/TasteIt.Web/Views/Recipes/Index.cshtml
@model TasteIt.Web.Models.Recipe.RecipesIndexViewModel
@{
    ViewBag.Title = "Recipe";
}

<h1 class="text-center">Recipes with <i class="logo">Taste It!</i></h1>
<hr />
<h2 class="text-center logo">Select recipe by:</h2>
<hr />

@if (this.User.Identity.IsAuthenticated)
{
    @Html.ActionLink("Create recipe", "/Create", "Recipes", null, new { @class = "btn btn-primary" })
}

<div class="container selected-items">
    <div class="row">
        <div class="col-md-6">
            <h4 class="recipe-categ-title"><strong>Recipes by season:</strong></h4>
            <ul class="detail-text">
                @foreach (var recipe in Model.Recipes.OrderBy(x => x.Occasion))
                {
                    <li><a href="Recipes/GetBySeason?season=@recipe.Season.ToString()">@recipe.Season.ToString()</a></li>
                }
            </ul>
        </div>


        <div class="col-md-6">
            <h4 class="recipe-categ-title"><strong>Recipes for special occations:</strong> </h4>
            <ul class="detail-text">
                @foreach (var occasion in Model.Occasions)
                {
                    <li><a href="Recipes/GetByOccasion?occasion=@occasion.Name">@occasion.Name</a></li>
                }
            </ul>
        </div>
    </div>
</div>

<hr />
<h2 class="text-center logo">All recipes:</h2>
<hr />

@Html.Partial("_RecipePartial");

TasteIt/Web/TasteIt.Web/Views/Recipes/_RecipePartial.cshtml
@model TasteIt.Web.Models.Recipe.RecipesIndexViewModel
@{
    ViewBag.Title = "_RecipePartial";
}

<div class="row">
    @foreach (var recipe in Model.Recipes)
    {
        <div class="col-md-4 text-center">
            <div class="container-articles">
                <h4 class="section-subtitles">
                    <strong>
                        @Html.ActionLink(recipe.Title, "/Details" + recipe.Url, "Recipes")
                    </strong>
                </h4>
                <p>
                    <span class="glyphicon glyphicon-heart"></span>@recipe.Likes.Sum(v => (int)v.Value)
                    <span class="glyphicon glyphicon-comment"></span> @recipe.Comments.Count()
                </p>
                <img src="@recipe.RecipeImage" class="images-home" />
            </div>
        </div>

    }
</div>